# Remote state backend (GCS).
#
# The state bucket is NOT created by this root module (chicken-and-egg: the
# backend is read before any resource is provisioned). It is created by
# scripts/bootstrap-gcp.sh, which also writes the resolved bucket name into
# backend.hcl. Initialize with:
#
#   terraform init -backend-config=backend.hcl
#
# backend.hcl (generated by bootstrap) looks like:
#   bucket = "qassistant-tfstate-<project_id>"
#   prefix = "qassistant/mvp"
#
# The empty "gcs" block below makes Terraform require -backend-config values
# at init time rather than hard-coding a bucket name into version control.
terraform {
  backend "gcs" {}
}
